    roles = ['Director', 'Writer', 'Producer', 'Voice', 'Animator', 'Audio', 'Intern', 'Character Designer', 'Lead Animator', 'Creator']

    tags = [
      'Absract',
      'Robot',
      'Aliens',
      'Angels',
      'Baseball',
      'Bounty Hunters',
      'Cars',
      'Dinosaurs',
      'Dragons',
      'Food',
      'Monster-of-the-week'
    ]

    genres = [
    'Giant-robot',
    'Racing',
    'Sports',
    'Slice-of-life',
    'Comedy',
    'Adventure',
    'Magical Girl'
    ]


    anime = ['Bad Girl Mode',
    'Cautious Pe Mami',
    'Combat Maid Admirals',
    'Cultural Stone Shadow',
    'Eyepatch Neun',
    'General Armageddon',
    'Initial Glass Hell Marines',
    'Magic Drei',
    'My Pretty Magic Corrector Tau',
    'Natural Outrage Beats',
    'Ninja Restraunt',
    'Neo Speed Mermaid Doctors',
    'Ogre Girl Zeshin',
    'Our Justice Beats',
    'Planetary Moon Zone',
    'Power Trooper Espers',
    'Prince Lover Mutants',
    'Prince \ Marionnete',
    'Professor Space',
    'Revelation Robots',
    'Secret Zepplin',
    'Teacher Twilight',
    'Time Layers',
    'Total Thunder Asassin Phi',
    'Weather Sorcerors',
    'Battler Savior',
    'Bebop Professor Princess Honey',
    'Big Dream Cop Troopers',
    'Bubblegum Fairy Searphim',
    'Detective Honey',
    'Dynamic Twilight Dragon Phantom',
    'Experiment Rogue Sirens',
    'Formula Climber Demon',
    'Her Rogue Oblivion Wedding Hundred',
    'His Charming Captain Cognition',
    'Hit Collector Mortals',
    'Lord Ice Alpha',
    'Lost Major Rage',
    'Lover One-Hundred Yutaka',
    'Major Detonator Twins',
    'Miracle : Rage',
    'Nighttime Admiral Asassin Rock',
    'Our Army Zeshin',
    'Siren Adventures',
    'Strike Phantom Warriors',
    'Submarines of Jin',
    'Super-dimensional Barbaric Hades Omega',
    'Super-dimensional Queen Monster Troopers',
    'Teacher Mistress Maids',
    'World Mistress Seekers',
    'Abominable Unthinkable Devil Odin',
    'Angel Love Brides',
    'Battleship Idol Espers',
    'Big Last Alliance Singer Nu',
    'Blade Knight Captors',
    'Boy Planet U',
    'Candy Mermaids Twins',
    'Dream of Eiko',
    'Evil Captain Bounty',
    'Geo Yod',
    'Giant Mighty Metal Express',
    'Gladiators Crown',
    'Gladiators Wonder',
    'Gunsmith Maze',
    'Hell Gender Mu',
    'Hunter Teth Yoshimasa',
    'Layer Thief Ronin',
    'Our Chimera Jumper Lady Tadako',
    'Outrageous Salvation General Fool Akihiko',
    'Psycho Miss Magic-User Troopers',
    'Robot Female Guerillas',
    'Sailor Tokyo',
    'Spirit Journey',
    'Truck \ Showdown',
    'Velocity Omega']